/*
 *
 *  Copyright (c) 2013 Berner Fachhochschule, Switzerland.
 *   Bern University of Applied Sciences, Engineering and Information Technology,
 *   Research Institute for Security in the Information Society, E-Voting Group,
 *   Biel, Switzerland.
 *
 *   Project independent UniVoteVerifier.
 *
 */
package ch.bfh.univoteverifier.action;

import ch.bfh.univoteverifier.gui.ConsolePanel;
import ch.bfh.univoteverifier.gui.MainGUI;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JMenuItem;

/**
 * An Action that manages the action of changing the language of the program.
 *
 * @author prinstin
 */
public class ChangeLocaleAction extends AbstractAction {

	MainGUI mainGUI;

	/**
	 * Create an instance of this Action.
	 *
	 * @param consolePanel a reference to
	 */
	public ChangeLocaleAction(MainGUI mainGUI) {
		this.mainGUI = mainGUI;

	}

	/**
	 * This method is called when an action is performed on a component to
	 * which this Action has been registered
	 *
	 * @param e ActionEvent generated by the component on which an action
	 * was performed.
	 */
	@Override
	public void actionPerformed(ActionEvent e) {
		String name = ((JMenuItem) e.getSource()).getName();
		String text = "";
		if (0 == name.compareTo("btnEn")) {
			text = "locale changed to english";
		} else if (0 == name.compareTo("btnFr")) {
			text = "locale changed to french";
		} else if (0 == name.compareTo("btnDe")) {
			text = "locale changed to german";
		}
		mainGUI.appendToConsole(text);
	}
}
