/**
*
*  Copyright (c) 2013 Berner Fachhochschule, Switzerland.
*   Bern University of Applied Sciences, Engineering and Information Technology,
*   Research Institute for Security in the Information Society, E-Voting Group,
*   Biel, Switzerland.
*
*   Project independent UniVoteVerifier.
*
*/
package ch.bfh.univoteverifier.action;

import ch.bfh.univoteverifier.gui.GUIconstants;
import ch.bfh.univoteverifier.gui.MainGUI;
import java.awt.event.ActionEvent;
import java.util.ResourceBundle;
import javax.swing.AbstractAction;
import javax.swing.JCheckBoxMenuItem;

/**
 * An Action class that manages the action of clicking on the show console menu time.
 * It toggles the visibility of the console-like GUI text area for system
 * messages.
 *
 * @author prinstin
 */
public class ShowConsoleAction extends AbstractAction {

    MainGUI mainGUI;

    /**
     * Create an instance of this Action class.
     *
     * @param MainGUI Send as reference to be able to use the 'callback' type
     * method to toggle the visibility of the console.
     */
    public ShowConsoleAction(MainGUI mainGUI) {
        ResourceBundle rb = ResourceBundle.getBundle("error", GUIconstants.getLocale());
        this.putValue(NAME, rb.getString("showConsole"));
        this.mainGUI = mainGUI;
    }

    /**
     * This method is called when an action is performed on a component to which
     * this Action has been registered
     *
     * @param e ActionEvent generated by the component on which an action was
     * performed.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        JCheckBoxMenuItem mItem = (JCheckBoxMenuItem) e.getSource();
        boolean selected = mItem.getState();
        mainGUI.showConsole(selected);
    }
}
